In [1]:
from IPython.display import clear_output
from copy import copy,deepcopy #Utilizamos esta funcion para copiar las matrices
import numpy as np #para la gestion de los arrays 2d
import matplotlib.pyplot as plt #Para mostrar los nudos.
from operator import itemgetter
from random import randrange, choice, shuffle
np.set_printoptions(threshold=np.inf,linewidth=np.inf,nanstr="n")
from Path import *
from CustomKnot import *


In [2]:
def randomMov(knot,debug=False):
    typeMov = randrange(1,4)
    if debug: print("-------") 
    n = knot.numberOfStrands
    if debug: print("number Of Strands:",n)
    if debug: print(k)
    if debug: print("type, ", typeMov)
    if typeMov == 1:
        createOrUndo = randrange(2) 
        if createOrUndo:
            if debug: print("Create")
            if n == 0:
                strandToCreate = 1
            else:
                strandToCreate = randrange(1,n+1)
            if debug: print("strandToCreate",strandToCreate)
            orientation = randrange(4)
            knot.crateALoop(strandToCreate,orientation)
            if debug: print("Hecho",strandToCreate,"orientation: ",orientation)
        else:
            if debug: print("undo")
            posibleCross = [cross for cross in knot.crosses if knot.isPosibleUndoALoop(cross)]
            if len(posibleCross)>0:
                randomCross = choice(posibleCross)
                if debug: print("randomCross",randomCross)
                knot.undoALoop(randomCross)
                if debug: print("Hecho",randomCross)
    elif typeMov == 2:
        createOrUndo = randrange(2)
        if debug: print("create") if createOrUndo else print("undo")
        possibilities = [(l1,l2) for l1 in range(1,n) for l2 in range(1,n)]
        if not createOrUndo: possibilities = [(l1,l2) for (l1,l2) in possibilities if (knot.typeOfStrand(l1) == StrandType.ABOVE and knot.typeOfStrand(l2) == StrandType.BELOW) or (knot.typeOfStrand(l1) == StrandType.BELOW and knot.typeOfStrand(l2) == StrandType.ABOVE)]
        shuffle(possibilities)
        while possibilities:
            (l1,l2) = possibilities.pop(0)
            if createOrUndo:
                orientation = randrange(2)
                if debug: print(l1,l2,orientation)
                if knot.createReidemeisterII(l1,l2,orientation):
                    if debug: print("Hecho",l1,l2, "orientation", orientation)
                    break
            else:
                if debug: print("intentando:", l1,l2)
                if knot.undoReidemeisterII(l1,l2):
                    if debug: print("Hecho",l1,l2)
                    break
    elif typeMov == 3:
        possibilities = {StrandType.ABOVE:[], StrandType.MIDDLE:[],StrandType.BELOW:[]}
        
        for l in range(1,n):
            t = knot.typeOfStrand(l)
            possibilities[t].append(l)
        possibilities = [(l1,l2,l3) for l1 in possibilities[StrandType.BELOW] for l2 in possibilities[StrandType.MIDDLE] for l3 in possibilities[StrandType.ABOVE]]
        possibilities = [(l1,l2,l3) for (l1,l2,l3) in possibilities if mod(l1+1,n)!=l2 and mod(l1-1,n)!=l2 and mod(l1+1,n)!=l3 and mod(l1-1,n)!=l3 and mod(l2+1,n)!=l3 and mod(l2-1,n)!=l3]
        shuffle(possibilities)
        while possibilities:
            (l1,l2,l3) = possibilities.pop(0)
            print(l1,l2,l3)
            if knot.reidemeisterIII(l1,l2,l3,check=False):
                if debug: print("Hecho III")
                break
        if debug: print("No se puede hacer")

In [3]:
k = CustomKnot([
  X(1,9,2,8),
  #X(2,8,1,9),
  X(3,10,4,11), 
  X(5,3,6,2),
  X(7,1,8,12), 
  X(9,4,10,5), 
  X(11,7,12,6)])
c = 0
while c<=100:
    randomMov(k,True)
    c+=1
print(k)

-------
number Of Strands: 12
Cross: [X(1,9,2,8), X(3,10,4,11), X(5,3,6,2), X(7,1,8,12), X(9,4,10,5), X(11,7,12,6)]
Planar Diagrams:
[[ 7  7  7  7  7  7  7  7  7  0  0  0  0  0  0  0  0]
 [ 7 12 12 12 12 12 12 12 -2 11 11 11  0  0  0  0  0]
 [ 7 12  0  0  0  0  0  0  6  0  0 11  0  0  0  0  0]
 [ 7 12  8  8  8  8  0  0  6  0  0 11  0  0  9  9  9]
 [ 7 12 -1  1  1 -2  2  2 -1  3  3 -2  4  4 -1  5  9]
 [ 7  7  7  0  0  9  0  0  5  0  0 10 10 10 10  5  9]
 [ 0  0  0  0  0  9  0  0  5  5  5  5  5  5  5  5  9]
 [ 0  0  0  0  0  9  9  9  9  9  9  9  9  9  9  9  9]]
type,  3
No se puede hacer
-------
number Of Strands: 12
Cross: [X(1,9,2,8), X(3,10,4,11), X(5,3,6,2), X(7,1,8,12), X(9,4,10,5), X(11,7,12,6)]
Planar Diagrams:
[[ 7  7  7  7  7  7  7  7  7  0  0  0  0  0  0  0  0]
 [ 7 12 12 12 12 12 12 12 -2 11 11 11  0  0  0  0  0]
 [ 7 12  0  0  0  0  0  0  6  0  0 11  0  0  0  0  0]
 [ 7 12  8  8  8  8  0  0  6  0  0 11  0  0  9  9  9]
 [ 7 12 -1  1  1 -2  2  2 -1  3  3 -2  4  4 -1  5  9]
 [ 7

In [1]:
class Widget(object):
    def __init__(self, arg=None):
        if arg:
            self.color_data = arg
        else:
            self.color_data = (0,0,0)

    def get_color(self):
        if type(self.color_data) is tuple:
            return self.color_data
        else:
            return str_to_tuple(self.color_data)

    def set_color(self, arg):
        self.color_data = arg

    # create property object to dispatch 'get' and 'set' methods
    # NOTE: "color" is a class attribute, not an instance attribute
    color = property(get_color, set_color)
w = Widget((1,1,2))
print(w.color)
w.color = (3,2,1)
print(w.color)

(1, 1, 2)
(3, 2, 1)
